FROM debian:jessie

RUN apt-get update
RUN apt-get install -y -q git unzip curl gcc make autoconf ncurses-dev python-pip
RUN pip install cram

RUN curl -L https://github.com/zsh-users/zsh/archive/@VERSION@.zip > @VERSION@.zip
RUN unzip @VERSION@.zip -d /usr/share/zsh 

WORKDIR /usr/share/zsh/zsh-@VERSION@

RUN rm -rf ./Doc
RUN mkdir ./Doc && echo "all:\n\n" > ./Doc/Makefile.in

RUN ./Util/preconfig
RUN ./configure --without-tcsetpgrp
RUN make
RUN make install.bin install.modules install.fns || :

RUN git config --global user.email test@test.test
RUN git config --global user.name test

RUN mkdir ~/.ssh
RUN echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

WORKDIR /
RUN rm @VERSION@.zip
RUN rm -rf /usr/share/zsh

